### ISSUE TITLE
Unable to monitor entire Dropbox folder hierarchy

### ISSUE THREAD

**Issue by dkunzler** [janeczku/docker-dropbox#11]
Hi,
I have a problem `docker logs` shows me the message 
```
Unable to monitor entire Dropbox folder hierarchy. Please run "echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p" and restart Dropbox to fix the problem.
```

However if I execute the command with `docker exec` ist says me it is unable to find user root. Executing just the first portion (without `sudo sysctl -p`) works but has no effect. (even after restarting the container)
```
[root@hostname ~]# docker exec cloud_dropbox_1 echo "fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p"
unable to find user root: no matching entries in passwd file
```

Anybody able to help me?

Regards
David

**Comment by janeczku** [comment]
`fs.inotify.max_user_watches` is a system-wide setting, so you need to set it on the host.
