### ISSUE TITLE
I'm getting "Dropbox isn't running!"

### ISSUE THREAD

**Issue by daaain** [janeczku/docker-dropbox#3]
Hey,

First of all thanks a lot for creating this image!

I'm having some problems though, while looking at `docker logs dropbox` I get the link URL and get `This computer is now linked to Dropbox. Welcome Dain`, but it doesn't seem to actually sync.

Also when I do a `docker exec -t -i dropbox dropbox status` or type `dropbox` inside the container I get `Dropbox isn't running!`.

I'm trying to map a volume into the Dropbox folder, have you tried that? Also to save the sensitive info locally to prevent having to log in every time. So something along the lines of:
```
docker volume create --name dropbox_volume
docker run -d --name=dropbox \
                  -e DBOX_UID=0 \
                  -e DBOX_GID=0 \
                  --volume dropbox_volume:/dbox/Dropbox/data \
                  --volume /Users/.../sensitive/dropbox:/dbox/.dropbox \
                  --restart=always \
                  janeczku/dropbox
```

Is there anything wrong with this?

**Comment by janeczku** [comment]
This is just a question of setting the `DBOX_UID` and `DBOX_GID` to the actual user owning the folder on the host. E.g. in your example owner of `/Users/.../sensitive/dropbox`.
Now, if you use Boot2Docker (which i suspect you do) then that folder is actually mounted and owned by 1000:50.
Here is a working example:
```Bash
$ docker volume create --name dropbox_volume
$ docker run -d --name=dropbox \
	-v dropbox_volume:/dbox/Dropbox \
	-v /Users/Janek/test/dropbox:/dbox/.dropbox \
	-e DBOX_UID=1000 \
	-e DBOX_GID=50 \
	janeczku/dropbox
```

**Comment by daaain** [comment]
Thanks a lot for the reply!

I realised that it's a stupid idea storing the Dropbox metadata on the local filesystem, as it won't be portable (like in this case making it specific to OS X + Boot2Docker). My use case is to use Dropbox to back up and synchronise a simple SQLite database and log files one way from the production server to development for a prototype (where doing something more robust isn't needed). The image I'm trying to connect the volumes to uses root user.

So with that in mind, I managed to make it work with the following:

```
docker volume create --name dropbox_volume
docker volume create --name dropbox_volume_metadata
docker run -d --name=dropbox \
                  -e DBOX_UID=0 \
                  -e DBOX_GID=0 \
                  --volume dropbox_volume:/dbox/Dropbox \
                  --volume dropbox_volume_metadata:/dbox/.dropbox \
                  --restart=always \
                  janeczku/dropbox
```

So the gotchas were:
1. trying to create the volume as a subdirectory under /dbox/Dropbox
2. using the local filesystem for metadata

Anyway, just wanted to share this so people trying to do the same don't need to scratch their heads!

Thanks again for the great image and pointing me to the right direction!

**Comment by dungv** [comment]
I use kubernetes to deploy janeczku\dropbox.  However, whenever the dropbox restarts, it always asks to reauthenticate again with https://www.dropbox.com/cli_link_nonc
Any way to re-store the credential so that we do have to re-authenticate again.

**Comment by eleaner** [comment]
@dungv 
did you sort it out?
