### ISSUE TITLE
How to save credential ?

### ISSUE THREAD

**Issue by rgarrigue** [janeczku/docker-dropbox#4]
Hi janeczku

Thanks for the good container. 

I'm wondering if there's some way to save the credential? Something like mounting the id file or database to avoid re-enabling the share through logs link whenever I regenerate my setup (which happen 100 times a day whenever I test some new stuff !)

Best regards,

**Comment by janeczku** [comment]
Hi,
The credentials are stored in the volume ` /dbox/.dropbox`. You could mount that to a local folder like this:

```SHELL
$ docker run -d --name=dropbox \
    -v /Users/Janek/test/dropbox:/dbox/.dropbox \
    -e DBOX_UID=1000 \
    -e DBOX_GID=50 \
    janeczku/dropbox
$ docker logs dropbox
```

You might have to set DBOX_UID and DBOX_GID to the user owning the host folder. See discussion here: https://github.com/janeczku/docker-dropbox/issues/3#issuecomment-179364590

**Comment by rgarrigue** [comment]
That did it, without the UID/GID. Thanks !
