### ISSUE TITLE
Disk usage in long running dropbox container

### ISSUE THREAD

**Issue by titpetric** [janeczku/docker-dropbox#6]
I figured out that dropbox has a tendency to self-update/download a new version of itself. It stores these things under /tmp, in folders like these:

```
root@dropbox:/tmp# du -sh .dropbox-dist-new-*
142M    .dropbox-dist-new-XNUozR
142M    .dropbox-dist-new-oIuDgE
142M    .dropbox-dist-new-rV_W6h
```

And also some under `/dbox`

```
root@dropbox:/dbox# du -sh .dropbox*
254M    .dropbox
166M    .dropbox-dist
61M     .dropbox-dist-tmp-31iEgN
128M    .dropbox-dist-tmp-S2eZ8J
133M    .dropbox-dist-tmp-cZJU7K
```

It seems also that all of the files in tmp are the same (no diff);

```
root@dropbox:/tmp# diff -qr .dropbox-dist-new-XNUozR/ .dropbox-dist-new-rV_W6h/
root@dropbox:/tmp# diff -qr .dropbox-dist-new-XNUozR/ .dropbox-dist-new-oIuDgE/
root@dropbox:/tmp#
```

I'm mounting the configs and the file volume with -v. When removing the container, and restarting the container I can reproduce the behaviour just with time:

```
root@serenity:/src/dropbox/bin# ./run status
Syncing (2,695 files remaining)
Indexing 2,695 files...
root@serenity:/src/dropbox/bin# ./run status
Upgrading Dropbox...
root@serenity:/src/dropbox/bin# ./run status
Syncing (5,292 files remaining)
Indexing 5,292 files...
root@serenity:/src/dropbox/bin# ./run status
Up to date
```

Docker logs:

```
root@serenity:/src/dropbox/bin# docker logs dropbox
DBOX_UID (user id) variable not specified, defaulting to 1000..
DBOX_GID (group id) variable not specified, defaulting to 1000..
dropboxd(3.14.7) started...
DBOX_UID (user id) variable not specified, defaulting to 1000..
DBOX_GID (group id) variable not specified, defaulting to 1000..
dropboxd(3.14.7) started...
```

ID 1000 is local user 'black', permissions for config folder are all set to black.black (and files were written by the container after starting up a clean instance).

```
root@serenity:/src/dropbox/conf# find -type f | xargs ls -lad | grep -v black
root@serenity:/src/dropbox/conf#
```

The whole `run` script I'm attaching just for posterity:

```
#!/bin/bash
NAME="dropbox"
DOCKERFILE="janeczku/dropbox:latest"

if [ ! -d "/mnt/dropbox" ]; then
        mkdir -p /mnt/dropbox
fi

RUNNING=$(docker inspect --format="{{ .State.Running }}" $NAME 2> /dev/null)
if [ "$RUNNING" != "true" ]; then
        docker pull $DOCKERFILE
        docker run -d --restart=always -h $NAME --name=$NAME -v /src/dropbox/conf:/dbox/.dropbox -v /mnt/dropbox:/dbox/Dropbox $DOCKERFILE
fi

if [ "$1" == "logs" ]; then
        docker logs dropbox
else
        docker exec -it dropbox dropbox $1
fi
```

Does anything pop out at you?

**Comment by janeczku** [comment]
Thanks for your detailed report. I am gonna have a look at it soon!

**Comment by janeczku** [comment]
I have changed the Dockerfile and made it remove write permissions from` /tmp` and `/dbox`. While i don't like this kind of hack it seems to be the only way to prevent dropbox from filling up the file system with these update files. The new image is currently building on Docker Hub so check it out if this solves the issue for you.

**Comment by titpetric** [comment]
It solves the issue for me. Dropbox doesn't restart, disk usage keeps at 0B overnight. Considering solved.

**Comment by titpetric** [comment]
Thank you very much :) Still waiting on info to send you a postcard! :)

**Comment by janeczku** [comment]
@titpetric So you are *still* enjoying the good life on Aruba? Looks like the holidays in Slovenia are almost as long as in Germany... I'd like to give you my address but i am kind of a private person as far as posting my data on the interwebs is concerned. By the way, the Dropbox image is now updating to the latest Dropbox version on container start. Check it out!

**Comment by titpetric** [comment]
@janeczku Aruba? No. Sao Miguel, Azores. It's more of a working remotely type of deal. I did kinda track down an old yahoo.de address of yours, I guess not correct. Feel free to send me a P.O. box number, work address or whatever on black@scene-si.org ... #notscamming :)

**Comment by janeczku** [comment]
@titpetric you got mail :smile:

**Comment by titpetric** [comment]
Thank you. I hope Portuguese mail works faster than Croatian so you'll get your postcard by summer :)

**Comment by janeczku** [comment]
@titpetric 🎉 👯  

![azoren](https://cloud.githubusercontent.com/assets/3813921/15518727/8c3dac9a-21fe-11e6-8ec6-52c53ff8af21.jpeg)

I bet that the Portuguese Mail Service is still using bottle post to ship from the Azores to the mainland. Would at least explain the 7 weeks delay. 😄

**Comment by titpetric** [comment]
Well, I almost mailed it on my last day :) but you might get two!
(interestinly, normal package arrived in about 10 days vs. 4 weeks for
postcards).

Take care ;)

Best,
Tit
