### ISSUE TITLE
Manage exclusions always returns "No directories are being ignored."

### ISSUE THREAD

**Issue by henrydobson** [janeczku/docker-dropbox#8]
I cannot successfully exclude and directories. I know that the exclude function can be picky but it seems to be impossible within the docker container. 

I have attempted the following.
`sudo docker exec -i -t dropbox dropbox exclude add Exclude`
`sudo docker exec -i -t dropbox dropbox exclude add /dbox/Dropbox/Exclude`

I also tried interacting with the container, changing to the /dbox/Dropbox directory and executing the exclude command there but no luck. 

Is this possible?

Thanks,

H

**Comment by sturple** [comment]
Hi @janeczku, @henrydobson 

I believe I am have the same issue.
I am using the  data mounted to local folder on the host

Thanks, 
Shawn

**Comment by janeczku** [comment]
Hi @henrydobson and @sturple , i didn't have time to look into this until today. This has been fixed in 01a47da9dd417dc27f88b998be5c5b0243a6dd0c. Updated images are building on Docker Hub right now.

**Comment by sturple** [comment]
Thanks @janeczku

**Comment by henrydobson** [comment]
Can confirm. Works great! Thanks @janeczku

**Comment by janeczku** [comment]
🎉 😄 👍
